sudo: true
dist: precise
language: emacs-lisp
env:
  matrix:
    - emacs=emacs-snapshot
    - emacs=emacs25

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo apt-get update -qq
  - sudo apt-get install -qq $emacs

script:
  - make update
  - make test
